//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProductManagement
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class ProductList
    {
        public int ProductID { get; set; }


        [Required(ErrorMessage ="Please Enter Product Name")]
        public string ProductName { get; set; }


        [Required(ErrorMessage = "Please Enter Category ID")]
        public string CategoryID { get; set; }


        [Required(ErrorMessage = "Please Enter Category Name")]
        public string CategoryName { get; set; }
    }
}
